code-insiders --install-extension enkia.tokyo-night
code-insiders --install-extension esbenp.prettier-vscode
code-insiders --install-extension foxundermoon.shell-format
code-insiders --install-extension mads-hartmann.bash-ide-vscode
code-insiders --install-extension mrmlnc.vscode-duplicate
code-insiders --install-extension rebornix.toggle
code-insiders --install-extension rogalmic.bash-debug
code-insiders --install-extension shakram02.bash-beautify
code-insiders --install-extension ssigwart.trailing-whitespace-fixer
code-insiders --install-extension whizkydee.material-palenight-theme
code-insiders --install-extension yy0931.gitconfig-lsp
