code --install-extension aaron-bond.better-comments
code --install-extension akmarnafi.comment-headers
code --install-extension albert.tabout
code --install-extension alefragnani.bookmarks
code --install-extension alefragnani.project-manager
code --install-extension alexisvt.flutter-snippets
code --install-extension alfredbirk.tailwind-documentation
code --install-extension analytic-signal.preview-pdf
code --install-extension andreabbondanza.ignoregit
code --install-extension anteprimorac.html-end-tag-labels
code --install-extension antfu.slidev
code --install-extension austenc.tailwind-docs
code --install-extension batisteo.vscode-django
code --install-extension bierner.emojisense
code --install-extension bierner.markdown-mermaid
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bodil.file-browser
code --install-extension bpruitt-goddard.mermaid-markdown-syntax-highlighting
code --install-extension bradlc.vscode-tailwindcss
code --install-extension carlocardella.vscode-filesystemtoolbox
code --install-extension chakrounanas.turbo-console-log
code --install-extension christian-kohler.npm-intellisense
code --install-extension codeium.codeium
code --install-extension codespaces-contrib.codeswing
code --install-extension codezombiech.gitignore
code --install-extension coenraads.bracket-pair-colorizer-2
code --install-extension compulim.vscode-clock
code --install-extension csstools.postcss
code --install-extension danielroedl.meld-diff
code --install-extension dart-code.dart-code
code --install-extension dart-code.flutter
code --install-extension davidanson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dbankier.vscode-quick-select
code --install-extension dionmunk.vscode-notes
code --install-extension donjayamanne.git-extension-pack
code --install-extension donjayamanne.githistory
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension electrotype.windows-explorer-context-menu
code --install-extension eliostruyf.vscode-hide-comments
code --install-extension eliverlara.andromeda
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension foxundermoon.shell-format
code --install-extension github.codespaces
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension github.vscode-pull-request-github
code --install-extension grapecity.gc-excelviewer
code --install-extension gruntfuggly.todo-tree
code --install-extension henriquebruno.github-repository-manager
code --install-extension hoovercj.vscode-power-mode
code --install-extension htmlhint.vscode-htmlhint
code --install-extension huizhou.githd
code --install-extension humao.rest-client
code --install-extension hyesun.py-paste-indent
code --install-extension ibm.output-colorizer
code --install-extension jacobdufault.fuzzy-search
code --install-extension johnpapa.vscode-peacock
code --install-extension kahole.magit
code --install-extension kevinrose.vsc-python-indent
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension lamartire.git-indicators
code --install-extension letmaik.git-tree-compare
code --install-extension liviuschera.noctis
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension mathpix.vscode-mathpix-markdown
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension mikestead.dotenv
code --install-extension moalamri.inline-fold
code --install-extension ms-1es.pull-request-quantifier
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.black-formatter
code --install-extension ms-python.pylint
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.live-server
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-repositories
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.vscode-github-issue-notebooks
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension nash.awesome-flutter-snippets
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension oderwat.indent-rainbow
code --install-extension olivertasevski.vscode-space
code --install-extension onlylys.leaper
code --install-extension orta.vscode-jest
code --install-extension peterschmalfeldt.explorer-exclude
code --install-extension pkief.material-icon-theme
code --install-extension pomdtr.excalidraw-editor
code --install-extension quicktype.quicktype
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension robbowen.synthwave-vscode
code --install-extension robole.file-bunny
code --install-extension ryanluker.vscode-coverage-gutters
code --install-extension shaharkazaz.git-merger
code --install-extension simonsiefke.svg-preview
code --install-extension sketchbuch.vsc-quokka-statusbar
code --install-extension stateful.runme
code --install-extension stivo.tailwind-fold
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-spanish
code --install-extension sumneko.lua
code --install-extension t-sauer.autolinting-for-javascript
code --install-extension telesoho.vscode-markdown-paste-image
code --install-extension tim-koehler.helm-intellisense
code --install-extension timkmecl.chatgpt
code --install-extension timmoverlaan.uri-open-recent
code --install-extension timonwong.shellcheck
code --install-extension tomsaunders.vscode-workspace-explorer
code --install-extension tonybaloney.vscode-pets
code --install-extension tyriar.sort-lines
code --install-extension tyriar.vscode-terminal-here
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension visualstudioexptteam.vscodeintellicode-completions
code --install-extension vscodevim.vim
code --install-extension vsls-contrib.codetour
code --install-extension vsls-contrib.gistfs
code --install-extension vsls-contrib.gitdoc
code --install-extension vspacecode.vspacecode
code --install-extension vspacecode.whichkey
code --install-extension vstirbu.vscode-mermaid-preview
code --install-extension wallabyjs.quokka-vscode
code --install-extension wayou.vscode-todo-highlight
code --install-extension wenfangdu.snippet-generator
code --install-extension wholroyd.jinja
code --install-extension wilhelmer.status-bar-pull-push
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension zignd.html-css-class-completion
code --install-extension ziyasal.vscode-open-in-github
